version: "3"

services:
  web:
    build:
      dockerfile: ./_docker/nginx/Dockerfile
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8877:80"
    depends_on:
      - app
    container_name: nginx_app
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    depends_on:
      - db
    container_name: php_app
  db:
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker_php
      MYSQL_ROOT_PASSWORD: root
#    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: php_db

volumes:
  mysqldata: